apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8sm0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0045-tenant/ci1t-830-0045-app/devfile-sample-8sm0@sha256:33faf6421dd5d5d0abccfbc4dae3d09abd4b473f24d9f07cd18dc8fb003a73f9
        name: my-nodejs
        resources: {}
status: {}
