apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8sm0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8sm0
    app.kubernetes.io/part-of: ci1t-830-0045-app
  name: devfile-sample-8sm0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8sm0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8sm0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0045-tenant/ci1t-830-0045-app/devfile-sample-8sm0@sha256:33faf6421dd5d5d0abccfbc4dae3d09abd4b473f24d9f07cd18dc8fb003a73f9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
